name: CI

on:
    pull_request:
        branches: ["master"]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Setup node.js 16.x
              uses: actions/setup-node@v3.3.0
              with:
                  node-version: 16.x

            - run: npm ci

            - name: Vitest with coverage
              run: npm test

            - name: Test build
              run: npm run build
